name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build services
        run: |
          dotnet restore ./services/user-service/UserService.csproj
          dotnet restore ./services/product-service/ProductService.csproj
          dotnet restore ./gateway/Gateway.csproj
          dotnet build ./services/user-service/UserService.csproj --configuration Release
          dotnet build ./services/product-service/ProductService.csproj --configuration Release
          dotnet build ./gateway/Gateway.csproj --configuration Release

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build images with compose
        run: docker compose build

      - name: Push images
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/user-service:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/product-service:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/gateway:latest
